Check main.js and main.css files after build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,6 +13,15 @@ jobs:
             npm install
             npm test
             npm run build
+            if [ ! -f build/static/js/main.js ] || [ ! -f build/static/js/main.js.map ]; then
+              echo "main.js or main.js.map not found"
+              exit 1
+            fi
+
+            if [ ! -f build/static/css/main.css ] || [ ! -f build/static/css/main.css.map ]; then
+              echo "main.css or main.css.map not found"
+              exit 1
+            fi
       - persist_to_workspace:
           root: ~/hetmech-frontend
           paths:
