Check build files (#151)
Check main.js and main.css files after build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,7 +3,7 @@ version: 2
 jobs:
   test:
     docker:
-      - image: node:8.15.1-stretch
+      - image: circleci/node:latest
     working_directory: ~/hetmech-frontend
     steps:
       - checkout
@@ -13,6 +13,15 @@ jobs:
             npm install
             npm test
             npm run build
+            if [ ! -f build/static/js/main.js ] || [ ! -f build/static/js/main.js.map ]; then
+              echo "main.js or main.js.map not found"
+              exit 1
+            fi
+
+            if [ ! -f build/static/css/main.css ] || [ ! -f build/static/css/main.css.map ]; then
+              echo "main.css or main.css.map not found"
+              exit 1
+            fi
       - persist_to_workspace:
           root: ~/hetmech-frontend
           paths:
@@ -29,7 +38,7 @@ jobs:
       - run:
           name: Install and configure dependencies
           command: |
-            sudo npm install --global --silent gh-pages
+            npm install --silent gh-pages
       - add_ssh_keys:
           fingerprints:
             - "59:f7:cc:2f:9e:bf:97:12:46:a0:16:60:a2:3b:13:2a"
@@ -38,9 +47,7 @@ jobs:
           command: |
             echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
             touch build/.nojekyll  # Disable Jekyll processing on GitHub Pages
-            sudo mkdir -p /usr/local/lib/node_modules/gh-pages/.cache/
-            sudo chmod 777 /usr/local/lib/node_modules/gh-pages/.cache/
-            gh-pages --dist build \
+            ./node_modules/.bin/gh-pages --dist build \
               --user "CircleCI Deploy Job <ci-build@circleci.com>" \
               --message \
             "Deploy webpage on `date --utc --iso-8601`
